Clearing the MessagingClient code .
ManageIQ/topological_inventory-ansible_tower pull request #139
Opened 2020-10-23 11:32 UTC by pkomanek

2020-10-23 12:38 UTC, slemrmartin approved these changes
:+1: LGTM

2020-10-23 14:00 UTC, slemrmartin requested changes
I forgot in my review that Gemfile has to be updated

2020-10-23 18:18 UTC, lindgrenj6 approved these changes

2020-11-19 09:55 UTC, slemrmartin approved these changes

2020-11-19 09:56 UTC, merged