Add external_url logging to collector
ManageIQ/topological_inventory-ansible_tower pull request #82
Opened 2020-04-07 22:02 UTC by lindgrenj6

https://projects.engineering.redhat.com/browse/TPINVTRY-881
This is the tower collector implementation for this ticket. 

Looking for input on this. currently it logs like so: 
![image](https://user-images.githubusercontent.com/5856504/78723586-5531cd00-78f1-11ea-9d5e-938f096dc42c.png)

Potential things I may be missing:
- should we add parameters to the logging?
- maybe I could move this to the base collector class since it's just one method and it could be used across all of the collectors, that way we can just call this moethod in each `get_#{resource_type}` method call.

cc @gmcculloug @slemrmartin

2020-04-08 08:40 UTC, slemrmartin requested changes
I would rather extend these logs: 
- https://github.com/RedHatInsights/topological_inventory-ansible_tower/blob/master/lib/topological_inventory/ansible_tower/collector.rb#L64
- https://github.com/RedHatInsights/topological_inventory-ansible_tower/blob/master/lib/topological_inventory/ansible_tower/collector.rb#L96
- https://github.com/RedHatInsights/topological_inventory-ansible_tower/blob/master/lib/topological_inventory/ansible_tower/collector.rb#L105

by external_url, because the first one is always preceding all these logs without any significant operation (and 2nd/3rd logs are closing the 1st). 
Similarly to all collector repos

2020-04-08 08:40 UTC, slemrmartin commented on lib/topological_inventory/ansible_tower/collector/service_catalog.rb
> +        logger.info("[EXTERNAL URL] #{tower_hostname}/api/v2/#{connection_class.klass.endpoint}")
You can use `connection.api_url(tower.hostname)` instead of hardcoded version

2020-04-08 18:37 UTC, agrare commented
@slemrmartin since the entity_type != `connection.api.foo` I don't think we'd be able to log more than just the tower base url URL if it was done in the collector_thread.

2020-04-24 17:47 UTC, syncrou reviewed
>maybe I could move this to the base collector class since it's just one method and it could be used across all of the collectors, that way we can just call this moethod in each get_#{resource_type} method call.

☝️ I like this idea.  It seems per @agrare's comment and what I've learned from the current logs that we can't get access to what we actually need to log if we try extending them.

But having the use of a shared method off the base makes a lot of sense to me.

2020-04-27 20:09 UTC, lindgrenj6 commented
@syncrou https://github.com/RedHatInsights/topological_inventory-providers-common/pull/18

Opened PR on common collector to move the method.

2020-04-28 12:43 UTC, slemrmartin approved these changes

2020-04-29 10:12 UTC, slemrmartin commented
https://github.com/RedHatInsights/topological_inventory-providers-common/pull/20 
This is a blocker for this PR

2020-05-08 18:17 UTC, syncrou approved these changes
LGTM 👍 Happy to get this in.

2020-05-08 18:18 UTC, merged